# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cdb8e49ea0b30f8dec626faee9612280d5d54c876f56e83232c57c695d9a913c944583ce2147cca361cb25e2f577c6ea15bb6f219c44278e62fea3602dfaa0a

test:
  secret_key_base: e6d653c94d63ed399e82f677555c56cdeed6cae70cc00af7e2dffe8fd63bb4e8a1b315251aab268cb58c3acb7c2b53818504b24212b2682ab7d5b4bd4be37293

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
